### ISSUE TITLE
Too many "discarding unknown livedata message type" log messages

### ISSUE THREAD

**Issue by cope** [YuukanOO/streamy#11]
Hi YuukanOO,

I am getting the "discarding unknown livedata message type" log message on the client for all Streamy.broadcast messages, for both client and server side broadcasts.

I am simply broadcasting plain chat messages, nothing special.

Is there any way I can completely remove this debug statement?

**Comment by TomFreudenberg** [comment]
Hi @cope 

maybe you like to read this issue: #4

**Comment by YuukanOO** [comment]
Hi @cope!

As @TomFreudenberg already said, there is a workaround to prevent this issue, it's in the README:

> Note: Meteor keeps logging warning with _debug about the message not being recognized because of those lines. You can override Meteor._debug to get rid of it (as shown in the example).

The need for this hacky thing will be removed when a proper logging utility is available.

**Comment by cope** [comment]
Yup! That did it! :+1: 

THANKS! :)
