### ISSUE TITLE
Hello work example not working 

### ISSUE THREAD

**Issue by tomvolek** [YuukanOO/streamy#12]
HI :  I am doing  an application which I need to send a counter value from server to all my clients in the fastest way possible.  MongoDB collections are slow for me.  :)    I saw this package and trying to do a simple test as follows but I don't seem to get the output from my hello world on the client side.  

 Meteor.isServer {
    Streamy.BroadCasts.allow = function(data, from) {
              // from is the socket object    <= where do I get this socket from ?  
             // data contains raw data you can access:
            //  - the message via data.__msg
            //  - the message data via data.__data
             return true;
             };
    console.log("hello! from server ");
    Streamy.broadcast('hello', { data: 'world!' });
} 

if (Meteor.isClient) {    
    console.log("hello! from client ");
    // Attach an handler for a specific message
   Streamy.on('hello', function(d) {
   console.log("doing streamy stuff:",d.data); // Will print 'world!'
}

NOTE :  I am using Chrom, and on the Devloper-javascript console, If I type Streamy I see the Streamy object itself. 

Streamy
Object {BroadCasts: Object, DirectMessages: Object}BroadCasts: ObjectDirectMessages: Object_applyPrefix: (value)_sessionsEmit: (sid)_write: (data)broadcast: (message, data, except)connectHandlers: ()disconnectHandlers: ()emit: (message, data, to)handlers: (message)id: ()init: ()on: (message, callback)onConnect: (callback)onDisconnect: (callback)sessions: (sid)user: (socket)userId: (socket)__proto__: Object

**Comment by YuukanOO** [comment]
Hi @tomvolek !

> // from is the socket object <= where do I get this socket from ?

This socket is provided by Streamy when a client want to send a broadcast. You can retrieve a socket (server-side only) via `Streamy.sockets(session_id)`.

As for your example, this is simple. You call the broadcast immediately after the server has launched so the client may not be connected, I have successfuly tested this code:

```javascript
if(Meteor.isServer) {
  Streamy.BroadCasts.allow = function(data, from) {
    // from is the socket object <= where do I get this socket from ?

    // data contains raw data you can access:
    // - the message via data.__msg
    // - the message data via data.__data
    return true;
  };

  // When a client has connected
  Streamy.onConnect(function() {
    Streamy.broadcast('hello', { data: 'world!' });
  });

  console.log("hello! from server ");
}
else if (Meteor.isClient) {

  console.log("hello! from client ");
  // Attach an handler for a specific message
  Streamy.on('hello', function(d) {
    console.log("doing streamy stuff:",d.data); // Will print 'world!'
  });

}
```

I close this issue, if you have any other issue regarding the hello world sample, feel free to re-open.

**Comment by tomvolek** [comment]
HI Julien :
 Thanks for responding.   The example above works now.   What I am trying to to have a variable called counter on the server side which ticks every 80 microsecond,   I want to send every change on this value in a loop back to the connected clients . I use this value on the client side to draw a clock which ticks change base on this counter value received from server.   You can see the application here : http://flower_auction.meteor.com/      but currently I am using collections and if my code runs on a somewhat slow server like meteor.com , I notice not all the counter values which are a field increment in collection on server gets back to client.  as a result I miss some of the drawings of the dots on the clients side.  
I was looking for a way to have a reactiv variable on the server side, which I could receive them on client sides, and I noticed your package.  Do you think this is appropriate for what I want to do , or  I should do it another way ? 
ThanksTom
 


     On Thursday, August 20, 2015 12:51 AM, Julien LEICHER <notifications@github.com> wrote:
   

 Hi @tomvolek !
// from is the socket object <= where do I get this socket from ?
This socket is provided by Streamy when a client want to send a broadcast. You can retrieve a socket (server-side only) via Streamy.sockets(session_id).As for your example, this is simple. You call the broadcast immediately after the server has launched so the client may not be connected, I have successfuly tested this code:if(Meteor.isServer) {
  Streamy.BroadCasts.allow = function(data, from) {
    // from is the socket object <= where do I get this socket from ?

    // data contains raw data you can access:
    // - the message via data.__msg
    // - the message data via data.__data
    return true;
  };

  // When a client has connected
  Streamy.onConnect(function() {
    Streamy.broadcast('hello', { data: 'world!' });
  });

  console.log("hello! from server ");
}
else if (Meteor.isClient) {

  console.log("hello! from client ");
  // Attach an handler for a specific message
  Streamy.on('hello', function(d) {
    console.log("doing streamy stuff:",d.data); // Will print 'world!'
  });

}I close this issue, if you have any other issue regarding the hello world sample, feel free to re-open.—

**Comment by YuukanOO** [comment]
You could try to simulate the tick on the client side too. Keep your counter on collections, simulate on the client and when you receive the value by the server, it will take precedence over the client simulation.

If you decide to use Streamy, just call `Streamy.broadcast` in your tick ellapsed callback.

**Comment by tomvolek** [comment]
Thanks Julien for yoru suggestions.  I ended up using Streamy, and it is working great.  Even the code running on slow servers on meteor.com,  I am not missing my ticks on the server side . They all get back to the client vs before using bare collections.   I just did a broadcast from server side and put the streamy.on call inside a Tracker.on block.   
BY the way, is there a way to create reactivity on a simple variable/object ?  
RegardsTom

Here is my client code inside a Tracker.autorun.  
             var oldValue = 0;             var newValue = 0 ;             Tracker.autorun(function(){                                     // Attach an handler for a specific message               Streamy.on('hello', function(d) {                console.log("doing streamy stuff:",d.data); // Will print 'world!'                newValue = d.data ;                 if (newValue == 0 ){                                      drawPoint(newValue ,'white');                    drawPoint(0 ,'red');  //set the red dot top of the clock at 0                 }                else drawPoint(newValue,'red');                                if(oldValue != newValue ) {                    oldValue = newValue;                    // report that we have a new value                    // code here will run when we get an update                    if (newValue != 0 ) {                        drawPoint(newValue - 1,'white');                       // drawPoint(newValue,'red');                        console.log("NewValue:", newValue);                    }                                    }                    


     On Friday, August 21, 2015 12:27 AM, Julien LEICHER <notifications@github.com> wrote:
   

 You could try to simulate the tick on the client side too. Keep your counter on collections, simulate on the client and when you receive the value by the server, it will take precedence over the client simulation.If you decide to use Streamy, just call Streamy.broadcast in your tick ellapsed callback.—
