### ISSUE TITLE
Best way to have simple private chat

### ISSUE THREAD

**Issue by tgoldenberg** [YuukanOO/streamy#14]
So I have the basic stream going with 'emit' and 'on' handlers, but what I would like to do is direct them to specific IDs. With Pusher, we would send a message to something like 'private-conversation.168', where 168 is the specific ID. Is there a way of dynamically emitting and sending data through Streamy in this way? My current code has <a href="https://gist.github.com/tgoldenberg/c4d2833b08ff2c3a0995">this</a>, without any specific IDs. I would like to be able to do <a href="https://gist.github.com/tgoldenberg/d391246defbb0ef5a703">this</a> though instead. Any suggestions?

**Comment by YuukanOO** [comment]
Hi! This is possible through [Streamy Rooms](https://github.com/YuukanOO/streamy-rooms). Add the package and you will be able to use:

```javascript
Streamy.rooms('my_room').emit('my_message', { data: 'Your data here' });
```
