### ISSUE TITLE
Easiest way to get the emitter's userId in .on()

### ISSUE THREAD

**Issue by gwendall** [YuukanOO/streamy#17]
The .on() callback on the client-side passes the sender's session ID as I see in [the doc](https://github.com/YuukanOO/streamy#streamybroadcastmessage_name-data-except_sids). 
In my case I would like to get the sender's userId. Is there an easy built-in way to get that?

**Comment by YuukanOO** [comment]
Nope but you can do it yourself when emitting. Something like this:

```javascript
// When emitting
Streamy.emit('your-message', { _uid: Meteor.userId(), other_data: 'Other value' });

// When receiving
Streamy.on('your-message', function(data) {
  console.log(data._uid, data.other_data);
});
```

**Comment by gwendall** [comment]
This is not ideal as anyone could basically "fake" being this other user. I ended up doing like that.

```
  Meteor.autorun(()=>{
    Tracker.autorun((tracker)=>{
      if (Meteor.userId() && Streamy.id()) {
        let selector = { _id: Meteor.userId() };
        let modifier = { $set: {'profile.socketSession': Streamy.id() }};
        Meteor.users.update(selector, modifier);
        tracker.stop();
      }
    });
  });
  let getUserId = (sessionId)=>{
    let user = Meteor.users.findOne({ 'profile.socketSession': sessionId });
    return user && user._id;
  };
  Streamy.on('your-message', (data)=>{
    let userId = getUserId(data.__from);
    // etc.
  });
```

**Comment by YuukanOO** [comment]
If I add it, should it be on another Library like [Rooms](https://github.com/YuukanOO/streamy-rooms) or should it be integrated in the core library?

**Comment by yayap13** [comment]
I think with the core.

**Comment by nlhuykhang** [comment]
@YuukanOO 
I think I can help you with this enhancement. My only concern is how the api should look like.
__from already points to sid, modifying it would be a bad idea.
How about a new field named __fromUserId?

**Comment by YuukanOO** [comment]
Sounds good to me ;)

**Comment by YuukanOO** [comment]
Thanks to @nlhuykhang !
