### ISSUE TITLE
feature request - kiss principle

### ISSUE THREAD

**Issue by TomFreudenberg** [YuukanOO/streamy#2]
Hi, first of all thanks to your work and sharing this with others.

I am working on IoT projects and therefor looking for "communication channels" between server and clients, where the server reads/gets information from the "things" and move them forward to clients.

I had created the forum entry

https://forums.meteor.com/t/meteor-and-the-internet-of-things-iot-whats-best-to-use-collection-meteor-streams-streamy/792

some days ago. By the moment we are deciding for a new project and for that I am testing available technics. Streamy is a cool one and we have it in out final decision but it looks to me that you may start to overload that great package.

In my personal opinion Streamy is something like a core extension and that is fine. I am strugling especially with your Rooms extension. For this e.g. you force the developer to add Streamy data (Rooms collection) to their app. Wouldnt it be better, if you create another package like "Streamy Rooms" if someone needs such a feature? 

I think "Direct Message" and "Broadcast" is something called core if someone is looking for a stream between client and server, all others are Extensions and should not be in core.

What do think about that.

Cheers,
Tom

**Comment by YuukanOO** [comment]
Yeah, that question came to me when I was developing streamy. You're right, I should move the rooms feature to a new package.

**Comment by TomFreudenberg** [comment]
Great ;-)

Thanks for feedback
Tom

**Comment by YuukanOO** [comment]
This is now done :) Thanks for your interest @TomFreudenberg !

**Comment by TomFreudenberg** [comment]
That was a fast one :-) Thanks a lot.
