### ISSUE TITLE
Does streamy support messaging using DDP?

### ISSUE THREAD

**Issue by PotterDai** [YuukanOO/streamy#20]
Really appreciate this package!
Just wondering, if this package support send/receive message through DDP?
If so which method should I call through DDP? Thank you. =)

**Comment by YuukanOO** [comment]
Could you be more specific? Do you want to catch collection update streamy side?

If so, I guess it would be possible but this package is here mainly to define your own message not to override existing ones.

**Comment by PotterDai** [comment]
Sorry if there is any confusion.
Since I'm currently using native iOS client to connect with Meteor through DDP websocket. I have to call Meteor's DDP methods (like "sub", "unsub", "add", etc), and then Meteor will respond to my DDP call if the method exists. 

Thus I was also wondering if streamy will also have a DDP API that I could call from DDP client.

**Comment by YuukanOO** [comment]
Not planned for now.
