### ISSUE TITLE
Streamy example does not work over production.

### ISSUE THREAD

**Issue by ronald2wing** [YuukanOO/streamy#23]
I had uploaded the streamy example to a meteor server here: http://oochos2.meteor.com/ but it is not work there.
Can you explain to me how can I use streamy over server?

**Comment by ronald2wing** [comment]
It worked now. Sorry for the inconvenience.

**Comment by ronald2wing** [comment]
It does not respond for the first few second. Any explanations?

**Comment by ronald2wing** [comment]
Streamy does not work with 1.2.1 meteor on production environment.
Here is the link with the Streamy example: http://oochos2.meteor.com/

**Comment by YuukanOO** [comment]
Look like it works now. Since meteor domain are loaded on demand, you may wait for the site to load first AFAIK.

**Comment by ronald2wing** [comment]
Yea. It work now thanks!
