### ISSUE TITLE
Emit not always firing on start-up

### ISSUE THREAD

**Issue by damienrobson** [YuukanOO/streamy#24]
Within the Streamy.onConnect() handler I have an emit which targets the connecting socket (excess code omitted):

``` javascript
Streamy.onConnect(function(socket) {
    Tracker.autorun(function() {
        var uid = Streamy.userId(socket);
        if (uid) {
            Streamy.emit('poll', {data: {profile: profile}}, socket);
        }
    }
}
```

Within the emit, I have a log message which reads, _Start Polling_, but I only see this if I:
1. log out and then back in again;
2. do a force-refresh in Chrome with CTRL-F5 (this sporadically works);
3. restart the Meteor server with the browser closed, and then opening `localhost` once the server has completely restarted.

Do you have any idea why this might be happening?

**Comment by YuukanOO** [comment]
This may be the `Tracker.autorun` but not sure of that.
