### ISSUE TITLE
can we integrate streamy in ionic client

### ISSUE THREAD

**Issue by AbhijitShivathare** [YuukanOO/streamy#27]
Hello, we want to integrate the streamy in ionic client. we have meteor as server and ionic as client. 
we want server able to send message or notify to client on some event.

Please help us.. 
Thanks.

**Comment by YuukanOO** [comment]
May be [socket.io](http://socket.io/) will be more appropriate for you. There is a tutorial to integrate it with ionic [here](https://www.airpair.com/ionic-framework/posts/ionic-socketio-chat-application-tutorial).

**Comment by AbhijitShivathare** [comment]
Thanks . I will check.
