### ISSUE TITLE
How is it useful to implement voice chat and video chat?

### ISSUE THREAD

**Issue by sandeepmeenuga** [YuukanOO/streamy#29]
I am not able to open example http://streamy.meteor.com/.
How is it useful to implement voice chat and video chat?
@YuukanOO

**Comment by YuukanOO** [comment]
Meteor does not support deploiement to `*.meteor.com` anymore and instead rely on [Galaxy](https://www.meteor.com/hosting).

**Comment by sandeepmeenuga** [comment]
Hi @YuukanOO ,

Thanks for your reply.

How is it useful to implement voice chat and video chat?

Can you suggest a video and Audio chat plugin or tool work with meteor .

**Comment by cope** [comment]
@sandeepmeenuga: Take a look here: http://stackoverflow.com/q/29831522/271873
