### ISSUE TITLE
Streamy not working on Cordova based android apps

### ISSUE THREAD

**Issue by SithMasterBDSM** [YuukanOO/streamy#34]
Streamy works like charm on standard Meteor web-based configuration, using google chrome browser, even on android mobile devices. After adding android platform to Meteor and building an apk to use the hybrid app using a webview, Streamy appears to just not connect to server. ¿how can this work? ¿does one need special permissions or configuration on mobile-config.js file?

**Comment by nlhuykhang** [comment]
I'm not really familiar with Cordova in Meteor. Could you provide more information about the issue? error message on console for example?

**Comment by SithMasterBDSM** [comment]
There is no error on console. The emitted messages simple does not reach the server. I think it is necessary to install this, meteor add-platform android, meteor build (this makes an apk) and then sign and install that apk to an android device to reproduce the issue.

**Comment by airstep** [comment]
+1

Error message is:

`Error: "Natives disabled"
    at (anonymous) (extensions::app:7:17)
TypeError: Cannot read property 'Binding' of undefined
    at extensions::runtime:7:46
Error: "Natives disabled"
    at (anonymous) (extensions::webstore:7:22)`

**Comment by airstep** [comment]
Sorry, I look at this again and after check it works now. Just change keypress event to keyup in js for android mode

**Comment by YuukanOO** [comment]
Thanks for reporting back @airstep ! Happy to hear that it's resolved for you. Closing it for now.
