### ISSUE TITLE
feature extenstion: Remove nasty _debug infos

### ISSUE THREAD

**Issue by TomFreudenberg** [YuukanOO/streamy#4]
Hi, I have created a feature request at meteors issue tracker to get better support for extensions like yours and to avoid nasty messages.

https://github.com/meteor/meteor/issues/4297

In the meantime, instead just deactivating all debug messages as you did in your example, I add here a reliable version for a debug extension.

Maybe you like to embed this to your example or README

To be placed into some of the client.js:

````
Meteor._debug = (function (super_meteor_debug) {
  return function (error, info) {
    if (info && _.has(info, 'msg'))
      super_meteor_debug("Streamy message is allowed!", info)
    else
      super_meteor_debug(error, info);
  }
})(Meteor._debug);
````

**Comment by TomFreudenberg** [comment]
Hi Julien, one additional remark:

In the README (Note:) I would suggest that you directly refer to the example part about the _debug override like

https://github.com/YuukanOO/streamy/blob/dc9433ad6602237d70dd2007bd74f5a290e70c25/examples/chat/client/app.js#L1-7

I would also suggest to change the remark 

https://github.com/YuukanOO/streamy/blob/dc9433ad6602237d70dd2007bd74f5a290e70c25/examples/chat/client/app.js#L1

to 

```
// Override Meteor._debug to filter for custom msgs
```

or similar.

Thanks,
Tom

**Comment by TomFreudenberg** [comment]
P.S.: I hope that you agree to the feature request at meteors issues list.

**Comment by YuukanOO** [comment]
Sure, they have also planned to develop a more featured logging utility.
