### ISSUE TITLE
Check message_name param for fix used Meteors ones

### ISSUE THREAD

**Issue by TomFreudenberg** [YuukanOO/streamy#5]
I have not made a test but this is just as a first reminder.

When looking at meteor source:

https://github.com/meteor/meteor/blob/c0aab1e8d3a5f01b4bedaa1c63dea3fc8f3db9b7/packages/ddp/livedata_connection.js#L223-259

there are some predefined msgs that should not be used as a message_name option when call e.g. 

```javascript
Streamy.broadcast('error', ... );
```

So I would suggest, that you validate that option when calling Streamy methods or you just add a static prefix to the message_name like `streamy_` to avoid conflicts.

**Comment by YuukanOO** [comment]
I'll go for the prefix :)

**Comment by TomFreudenberg** [comment]
Sorry to load you with work ;-)

Please give a short note if I should stop posting!

**Comment by YuukanOO** [comment]
Sorry for the delay ;)

**Comment by TomFreudenberg** [comment]
Hey Julien,

thanks for solving that! Works!
