### ISSUE TITLE
User information is not reactive on the server

### ISSUE THREAD

**Issue by xaxxon** [YuukanOO/streamy#7]
I want to send data down a stream from the server based on the user id associated with the stream.  While it can be looked up, how do I know if it changes?  

It would be nice if the user information was reactive on the server so I would know if the user information associated with the stream changed. 

Right now all I know to do is before every time I send something, to check every stream to see if it has the user I want connected on the other end.  A user can have multiple streams and I'd need to send to all of them.  

Basically I can't cache the data because every cached "matched" socket for a user I'd have to check to make sure it didn't stop being a match and every "not match" I have to check to make sure it didn't stop being a match - which means a full iteration over all of them, so no reason to cache.

On top of that, to know when a user has no more streams for their account, I have to poll all the connections periodically, as far as I can tell,  in case they logged out.  This can cause significant load even under conditions where there is no application activity taking place.

**Comment by TomFreudenberg** [comment]
Hi Zac ( @xaxxon )

maybe Streamy is not what you are looking for? You have not defined you usecase but it seems to me, that maybe a pub/sub collection with the right .find() is mor suitable.

Have a look at [this forum post](https://forums.meteor.com/t/meteor-and-the-internet-of-things-iot-whats-best-to-use-collection-meteor-streams-streamy/792/10) and check my MeteorPads.

Cheers
Tom

**Comment by xaxxon** [comment]
It doesn't seem like wanting to send information to only a certain user is
a strange use case.

**Comment by YuukanOO** [comment]
`onConnect` and `onDisconnect` is called when the ddp is up/down, and that's why userId is not set in it. I plant to had a `onLoggedIn` and `onLoggedOut`, maybe it can suit your needs?

**Comment by xaxxon** [comment]
Yes that would do it.  I just want some way to track

**Comment by xaxxon** [comment]
Yeah that would be perfect

**Comment by YuukanOO** [comment]
I finally implement reactive server-side `userId` in the version 1.2.0. Have a look at the documentation which contains a section for this use case : https://github.com/YuukanOO/streamy#streamyuseridsocket

**Comment by xaxxon** [comment]
Tracker.autorun is only supposed to be used on the client, according to the
docs.  I thought stuff like this was usually handled with just a callback
on the server side,

That's how things like accounts are done.

**Comment by YuukanOO** [comment]
So... Should I rewrite it?

**Comment by xaxxon** [comment]
I would ask on the forums what the impact is of using reactivity server
side.

https://forums.meteor.com
