### ISSUE TITLE
Streamy.id returns as undefined randomly.

### ISSUE THREAD

**Issue by jwktje** [YuukanOO/streamy#8]
This might be somewhat related to issue #7 
Client-side I'm getting the Session ID to send back to the server for one of the clients.
I'm doing this to let one client identify itself as the target/receiver for messages from the other clients.

For some reason the Streamy.id returnd als undefined sometimes causing the app to break.
The weird part is that the sid is logged in the debug message like this:
discarding unknown livedata message type Object {sid: "aaca5224-3862-4688-ab43-9b6d00c77ac4", msg: "streamy$sid"}

So it seems like the SID is generated but not accessible through Streamy.id.

Any help/fixes would be really appreciated. 

Apart from this, love the package!

**Comment by YuukanOO** [comment]
Maybe this issue appears because the message is emitted before the client callback is registered. I'll try to fix it asap.

**Comment by jwktje** [comment]
That seems plausible. The weird part is, after some (seemingly) unrelated code changes in totally different parts of the app it sometimes works again. The main problem is that it doesn't log any error when it doesn't work on either the server or the client.

I already compensate for the delay in which the client gets the SID and when the Streamy.id becomes available by recursively checking checking if it's defined with a timeout (up to 5 times). 

Gotta note again, than when it does work, the package works great! :D

**Comment by YuukanOO** [comment]
I started working on the related issue and switch the session id retrieved by `Streamy.id`. I used to retrieve the socket id (which was not available on the client) and now I use the connection id (available through `Meteor.connection._lastSessionId`), this should fix the issue in the upcoming version.

**Comment by jwktje** [comment]
Sounds perfect! Once it's available I will let you know my experience

**Comment by YuukanOO** [comment]
I close this issue since the new version (1.2.1) should fix this issue. `Streamy.id()` in `onConnect` callback should always be set. Feel free to reopen the issue if the bug is still present.

**Comment by cope** [comment]
Hi YuukanOO, I am getting the "discarding unknown livedata message type" log message on the client for all Streamy.broadcast messages, for both client and server side broadcasts.

I am simply broadcasting plain chat messages, nothing special.

Is there any way I can completely remove this debug statement?
