### ISSUE TITLE
Remove a stream?

### ISSUE THREAD

**Issue by turbogeek** [YuukanOO/streamy#9]
It is not clear how you would remove a stream. I need to be able to create and remove streams at will. 

My use case is that for a game, I need to create a stream with the ID of a unique game ID for only the game between players for the duration of the game (1 hour for example). At the end of the game, the game ID should no longer be used by anyone.

Is there a way to do this now, or is this something that needs to be added?

**Comment by YuukanOO** [comment]
I guess you could use [Rooms](https://github.com/YuukanOO/streamy-rooms) for this. What do you think?

**Comment by turbogeek** [comment]
Perhaps, I will take a look and see if it can work. Thank you for the suggestion.

Daniel Lee Brookshier
turbogeek@cluck.com
214-207-6614
